### ISSUE TITLE
FATFsMemSDHC throughput issue

### ISSUE THREAD

**Issue by dfukumori** [ErichStyger/mcuoneclipse#14]
Hi Erich,

http://mcuoneclipse.com/2012/07/30/fatfs-with-kinetis/#comment-16199

In the above comment, you mentioned that you weren't seeing any performance benefits using more data pins during SDHC communication. I believe this is due to the way that FATFsMemSDHC implements the disk_read and disk_write functions. Both of these functions use the following block of code to handle transferring multiple blocks to/from the SD card:

do {
      if (SD_TransferBlock(&SD, FALSE, sector*FATM1_BLOCK_SIZE, (uint8_t*)buff, 1)) {
        break;
      }
      sector++;
      buff += FATM1_BLOCK_SIZE;
    } while(--count);

Rather than performing one multi-block I/O operation, the component performs a number of single-block I/O operations. This incurs the SD card's read (or write) access time for each block transferred. A multi-block transfer would only incur this cost once.

I tested using 4-pin communication at 24MHz. A single 512-byte block read takes about 660us -- about 40us for the data transfer and 620us for the card-specific read access time. With the original disk read_function, reading n blocks takes n*(620us + 40us). I made some minor changes to disk_read and SD_TransferBlock so that they attempt to make a single multi-block read. Using the modified function, I saw times much closer to the ideal value of 620us + n*40us for n blocks.

**Comment by hanwannian** [comment]
if you use bigger block sizes and larger transfers you’ll get speed increases…. 10MB or 100MB files will run faster.

**Comment by hanwannian** [comment]
if you use bigger block sizes and larger transfers you’ll get speed increases…. 10MB or 100MB files will run faster.

**Comment by hanwannian** [comment]
I use the component more in SPI mode, and not much with SDHC. However, sometimes I have seen strange issues with SDHC, which appeard and then disappeared. I was never able to track it down :-(. looks like what you report could be the issue?

**Comment by ErichStyger** [comment]
As for SDHC, I even believe this could be some kind of silicon bug. I had sometimes issues too, not working it properly, but never found out why.
