### ISSUE TITLE
PE LED error on copy from KDS200 to KDS300 project

### ISSUE THREAD

**Issue by neilh10** [ErichStyger/mcuoneclipse#23]
Image of LedRedCopied:LED from KDS200 project.
It has error on Properties.Hw Interface. Pin "Error in the inherited component setting"
On attempting to change the Pin it can't find a suitable component
(Using KDS300 with latest mcuOnEclipse 05-July-2015 Release)
![image](https://cloud.githubusercontent.com/assets/2766619/8548859/4517fee0-247c-11e5-9b07-38d83b95e3b3.png)

If the LED is started from new it works OK
![image](https://cloud.githubusercontent.com/assets/2766619/8548881/6a0b69d0-247c-11e5-819e-ede589063f45.png)

**Comment by ErichStyger** [comment]
Ok, I see that problem on my end too. It seems to be related with the new Processor Expert component repositories. I have filed a bug report about this at Freescale.

**Comment by ErichStyger** [comment]
I have not heard from Freescale about a resolution of this issue.
