### ISSUE TITLE
FreeRTOS needs Shell named as CLS1

### ISSUE THREAD

**Issue by r-ben** [ErichStyger/mcuoneclipse#25]
With the recent PEComponents from 2015-11-22, FreeRTOS needs the enabled shell named as CLS1. 

The compiler throws 2 errors, if I name my shell e.g. SH1:

    arm-none-eabi-g++ -mcpu=cortex-m0plus -mthumb -Os -fmessage-length=0 -fsigned-char   -ffunction-sections -fdata-sections -ffreestanding -Wall -Wextra  -g -T ...   
    ./Generated_Code/FRTOS1.o: In function `PrintTaskList':
    ./Generated_Code/FRTOS1.c:186: undefined reference to `CLS1_SendStr'
    ./Generated_Code/FRTOS1.c:219: undefined reference to `CLS1_SendStr'
    collect2: error: ld returned 1 exit status

If I rename the shell to CLS1, everything is fine and the code is working.

**Comment by ErichStyger** [comment]
Thank you very much for reporting this!
I have fixed it now and the commited it:
https://github.com/ErichStyger/McuOnEclipse_PEx/commit/a37a02504fc7e5a6e6760d56eb8eb9fd6ae83ffb
