### ISSUE TITLE
SD_Card Component Doesn't allow selection of CS pin in SPIMaster_LDD

### ISSUE THREAD

**Issue by nlem** [ErichStyger/mcuoneclipse#28]
Hi Again Erich,

I'm using the SD_Card component driving an SPIMaster_LDD component.
The settings for SD_Card allow you to select the attribute sets to use for fast and slow mode.
That all seems to work.

The problem is that the attribute set number is used for selecting the CS line.
For example, if you use 0 for slow and 1 for fast, PEX emits the following:

#define SD1_SPI_SetSlowMode()              (void)SM2_SelectConfiguration(SM2_DeviceData, 0, 0)
#define SD1_SPI_SetFastMode()              (void)SM2_SelectConfiguration(SM2_DeviceData, 1, 1)

Unfortunately, most of the time, the user will want to use the same CS pin for both fast and slow mode.
PEX will not let you have 2 different CS configurations with the same pin so it's impossible to make this work.

The fix is to emit the same CS pin for each like below:

#define SD1_SPI_SetSlowMode()              (void)SM2_SelectConfiguration(SM2_DeviceData, 0, 0)
#define SD1_SPI_SetFastMode()              (void)SM2_SelectConfiguration(SM2_DeviceData, 0, 1)

It would also be possible to let the user select the CS pin for fast and slow mode, but I can't think of a situation where different CS pins would be needed.
 
Thanks,
Nick

**Comment by ErichStyger** [comment]
Hi Nick,
In my projects I'm using the same chip select pin both for fast and slow mode. The trick is that you should not set the CS pin the the SPIMaster_LDD: the CS pin is a normal pin and under control of the SD card component, and not of the SPI component. Or in other words: do not let the CS pin toggling by the SPI, this needs to be done by the SD card component.
I hope this helps.
