### ISSUE TITLE
InitUSB error with MKL26 with KSDK1.3

### ISSUE THREAD

**Issue by paloky** [ErichStyger/mcuoneclipse#30]
The Component "FSL_USB_Stack", have an error with inherit component InitUSB  with KSDS1.3.

**Comment by ErichStyger** [comment]
Do you mean the Kinetis SDK v1.3? If so, yes, these components are not compatible with the Kinetis SDK. You need to create a project *without* the Kinetis SDK if you want to use the FSL_USB_Stack component.

**Comment by ErichStyger** [comment]
Accidentially closed the issue, sorry. I'll keep it open for now. But to me this is a problem of the Kinetis SDK, not of the component :-(

**Comment by paloky** [comment]
Hi Erich.
Thanks for your fast response.
Can you tell me, (If it's possible) how can change the project propierties to don't use the SDK ?
Thanks a lot.

**Comment by ErichStyger** [comment]
You cannot change an existing project not to use the Kinetis SDK as far as I know.
You need to create a new project. There is a dialog while creating the project about which SDK to use. Select 'none' as SDK.
I hope this helps?

**Comment by paloky** [comment]
Thanks a lot.
I solved with other "non ortodox form".  I desinstall Eclipse SDK1.3 plugin, next I add FSL_USB_Stack component, and next I reinstall the SDK1.3.
It seem work OK now.
Thanks again.

**Comment by ErichStyger** [comment]
ok, great!
