### ISSUE TITLE
"Unknown macro" error when generating FreeRTOS component files

### ISSUE THREAD

**Issue by markdonkers** [ErichStyger/mcuoneclipse#37]
When the "Dynamic Allocation" is disabled under the "Memory" properties, the following error occurs:

Generator: FAILURE: at line 4785: Unknown macro: "LinkerHeapBaseSymbolName" (file: Drivers\sw\FreeRTOS.drv)	qg-h1		FRTOS1	Processor Expert Problem

I recently upgraded my ProcessorExpert components to the July 2017 release. Before this, I would never receive an error when "Dynamic Allocation" was disabled and "Static Allocation" was enabled. Unfortunately, I don't recall which release I had before performing the update.

**Comment by ErichStyger** [comment]
I apologize, I completely missed that report :-(.
I saw another report on this, and this is fixed in https://mcuoneclipse.com/2017/09/25/mcuoneclipse-components-25-sept-2017-release/. Can you try this one?

Thank you,
Erich
