### ISSUE TITLE
No re-enable interrupts

### ISSUE THREAD

**Issue by Pakequis** [ErichStyger/mcuoneclipse#39]
When a error is returned the interrupts are not re-enabled in the DHTxx.c.

**Comment by ErichStyger** [comment]
thanks for the report, I'll have a look.

**Comment by ErichStyger** [comment]
Thanks for catching (and reporting) this problem! Fixed now in https://github.com/ErichStyger/mcuoneclipse/commit/f58cadaa886c4aeee55754e86ef67a8f0e668273
Thanks again,
Erich
