### ISSUE TITLE
SDRAM DCD Settings for the Arch Mix board

### ISSUE THREAD

**Issue by tlukasiak** [ErichStyger/mcuoneclipse#44]
Hi,

I was curious if you have information on the SDRAM DCD settings for the Arch Mix board. SDRAM does not seem to be configured in the Arch Mix examples: https://github.com/ErichStyger/mcuoneclipse/blob/5691fc58d5e5a43d298f70c1349ce0f42b6111f1/Examples/MCUXpresso/i.MX%20RT1052%20Seeed%20Arch%20Mix/MIMXRT1052_Seeed_ArchMix_BlinkyFLASH/xip/evkmimxrt1050_sdram_ini_dcd.c#L31

Thanks

**Comment by ErichStyger** [comment]
No, I don't have any specific information about it. What I'm using is the information from the NXP SDK(s).
