### ISSUE TITLE
building tinyK22_RaspberryPi_UPS on linux: naming error

### ISSUE THREAD

**Issue by Daybreakerflint** [ErichStyger/mcuoneclipse#46]
Build error on linux:
fatal error: Buttons.h: No such file or directory application.c /tinyK22_RaspberryPi_UPS/source line 45 C/C++ Problem --> line 45: #include "buttons.h"

fatal error: InitPins.h: No such file or directory initPins.c /tinyK22_RaspberryPi_UPS/source line 7 C/C++ Problem --> line 7: #include "initPins.h"

fatal error: minIni.h: No such file or directory MinINI.h /tinyK22_RaspberryPi_UPS/McuLib/src line 58 C/C++ Problem --> line 58: //#include "minIni.h" commented and it builds

Those should fix the problem with building on linux

**Comment by ErichStyger** [comment]
Thanks for reporting!
Fixed with
https://github.com/ErichStyger/mcuoneclipse/commit/e6e9dfd7e970f49e838db2e632422edae0c5d39c
