### ISSUE TITLE
Cannot see anything in Image Info Tab of MCUXpressoIDE v11.2.1_4149?

### ISSUE THREAD

**Issue by Geek39** [ErichStyger/mcuoneclipse#47]
Hi all,

I have imported a project for the LPC11U68 in my workspace of MCUXpresso 11.2.1.
The project builds fine without errors. Only I see no info at all from the Image Info Tab!
Tried to copy this project into the workspace to see if this could make the difference, but the result is the same.

Have any of you guys have experienced this issue?
I would appreciate if anybody has a solution/guidance or workaround for this issue.
Thanks for help in advance!

Max

**Comment by ErichStyger** [comment]
I have seen issues with projects having links in it (it cannot find sources for it). Can you try with a later IDE (e.g. 11.5.0)?
