### ISSUE TITLE
McuSWO.c - SWO_PrintChar - The character is always sent to Stimulus port 0.

### ISSUE THREAD

**Issue by rogerdbenson** [ErichStyger/mcuoneclipse#49]
In McuSWO.c, in SWO_PrintChar, the port number is provided as a parameter, the the code always sends the character to port 0.

  while (ITM->PORT[0].u32 == 0) {
    /* Wait until STIMx is ready, then send data */
    timeout--;
    if (timeout==0) {
      return; /* not able to send */
    }
  }
  ITM->PORT[0].u8 = c;

**Comment by ErichStyger** [comment]
Thank you for reporting this, good catch! I always have just used port 0 :-(
Fixed and committed:
https://github.com/ErichStyger/McuOnEclipseLibrary/commit/1401065e2979140349d1884006907dd7d2716423
