### ISSUE TITLE
pico_LedCube - RP2350 support - 12 simultaneous output?

### ISSUE THREAD

**Issue by FeuerSturm** [ErichStyger/mcuoneclipse#51]
Hi,
would it be possible to enhance the pico_LedCube example to support the 12 PIO state machines of the new Pico 2 (RP2350) for 12 parallel outputs?

I'd be seriously interested to try to convert it into an Arduino library and use it as base for my USB HID LED Controller project then.

Thanks in advance!

**Comment by ErichStyger** [comment]
Yes, that should be possible. I already have ordered Pico 2 boards, but not received them yet.

**Comment by FeuerSturm** [comment]
Sounds great! Looking forward to it, thanks a lot!
