### ISSUE TITLE
FreeRTOS component fails to generate on HCS12

### ISSUE THREAD

**Issue by tai** [ErichStyger/mcuoneclipse#6]
It seems FreeRTOS PE component does not work with CodeWarrior for HCS12 v5.1 (PE v3.02), which is the latest (and the last) version of CW/PE for HCS12.

When I add FreeRTOS component, PE warns that a tick counter (TickCntr) component used by FreeRTOS has an error. Actual error found in TickCntr component window is: "Method Reset is not supported for selected device.".

Your website (http://www.steinerberg.com/EmbeddedComponents/FreeRTOS/) states that at least PE 3.09 service pack is needed. But the last version to support HCS12 is CW v5.1 + PE v3.02. Does this mean HCS12 is not supported anymore?

I'm not sure how to troubleshoot this.

I have FreeRTOS v8.0 running on my HCS12 board, so FreeRTOS surely still supports HCS12. And the warning given by PE also seems trivial, as I'm pretty sure there is some way to implement "Reset" functionality for any HCS12 timer/counter needed for system tick counting. Is there any way (say, editing some component bean file?) to suppress this error and allow me to implement needed function?

I'm using latest Part[12]_Beans_08.02.2014.PEupd checked out from github, with CW for HCS12 v5.1 (both special edition and eval edition, which I just installed now - so eval edition has all functionality enabled).

Best Regards,

**Comment by beszabo** [comment]
Hello, 

I can't download FreeRTOS_V8.0.0_23.02.2014.PEupd, the link is soon not valid. (And can't find it other place)

I have same problem with HCS12 and FreeRTOS as Tai.

Can you send me a valid link?

**Comment by ErichStyger** [comment]
The component releases are available on SourceForge: https://sourceforge.net/projects/mcuoneclipse/files/PEx%20Components/
